# Hypothesis Testing - Overview Exercises
Do your work for this exercise in a jupyter notebook named hypothesis_testing.ipynb.

For each of the following questions, formulate a null and alternative hypothesis (be as specific as you can be), then give an example of what a true positive, true negative, type I and type II errors would look like. Note that some of the questions are intentionally phrased in a vague way. It is your job to reword these as more precise questions that could be tested.

### 1. Has the network latency gone up since we switched internet service providers?

$H_{0}$ : There is no difference in network latency since we switched internet service providers.

$H_{\alpha}$ There has been an improvement in network latency since we switched internet service providers.

True Positive: If we reject $H_{0}$ and there is no difference in network latency.

True Negative: If we reject $H_{0}$ and there is an improvement in network latency.

Type I error (false positive): If we reject $H_{0}$ and that there is no difference in network latency. 

Type II error (false negative): If we fail to reject $H_{0}$ and that there is an improvement in network latency.


### 2. Is the website redesign any good?

$H_{0}$: There is no difference in website performance since the redesign. 

$H_{\alpha}$ There is an improvement in website performance since the redesign.

True Positive: If we reject $H_{0}$ and there is no difference in website performance.

True Negative: If we reject $H_{0}$ and there is an improvement in website performance.

Type I error: If we reject $H_{0}$ and that there is no difference in website performance. 

Type II error: If we fail to reject $H_{0}$ and that there is an improvement in website performance.

### 3. Is our television ad driving more sales?

$H_{0}$:  There is no difference in sales since airing the television ad.

$H_{\alpha}$:  There is an increase in sales since airing the television ad.

True Negative: If we fail to reject $H_{0}$ and there is no difference in sales.

True Postive: If we reject $H_{0}$ and there is an increase in sales.

Type I error: If we reject $H_{0}$ and that there is no difference in sales. 

Type II error: If we fail to reject $H_{0}$ and that there is an increase in sales.

### $chi^2$ Exercises

In [107]:
import numpy as np
import pandas as pd

from pydataset import data
from scipy import stats

## Use the following contingency table to help answer the question of whether using a macbook and being a codeup student are independent of each other.

 				Codeup Student	Not Codeup Student
	Uses a Macbook		49		20
	Doesn't Use A Macbook	1		30

### Form hypothesis

$H_o$: there is no association between being a codeup student and using a macbook

$H_a$: there is a association between being a codeup student and using a macbook

In [108]:
alpha = 0.05

### Make contigency tables

In [109]:
observed = pd.DataFrame([[49,20],[1,30]])
observed

0   1
0  49  20
1   1  30

### Calculate chi2 and p-value

In [110]:
chi2, p, degf, expected = stats.chi2_contingency(observed)

In [111]:
#output values
print('Observed')
print(observed.values)
print('\nExpected')
print(expected.astype(int))
print('\n----')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p}')

Observed
[[49 20]
 [ 1 30]]

Expected
[[34 34]
 [15 15]]

----
chi^2 = 36.6526
p     = 1.4116760526193828e-09


### Conclude

In [112]:
if p < alpha:
    print('We reject the null hypothesis')
else:
    print('We fail to reject the null hypothesis')

We reject the null hypothesis


## Choose another 2 categorical variables from the mpg dataset and perform a chi2 contingency table test with them. Be sure to state your null and alternative hypotheses.

In [113]:
#import data from pydataset
df = data('mpg')
df

manufacturer   model  displ  year  cyl       trans drv  cty  hwy fl  \
1           audi      a4    1.8  1999    4    auto(l5)   f   18   29  p   
2           audi      a4    1.8  1999    4  manual(m5)   f   21   29  p   
3           audi      a4    2.0  2008    4  manual(m6)   f   20   31  p   
4           audi      a4    2.0  2008    4    auto(av)   f   21   30  p   
5           audi      a4    2.8  1999    6    auto(l5)   f   16   26  p   
..           ...     ...    ...   ...  ...         ...  ..  ...  ... ..   
230   volkswagen  passat    2.0  2008    4    auto(s6)   f   19   28  p   
231   volkswagen  passat    2.0  2008    4  manual(m6)   f   21   29  p   
232   volkswagen  passat    2.8  1999    6    auto(l5)   f   16   26  p   
233   volkswagen  passat    2.8  1999    6  manual(m5)   f   18   26  p   
234   volkswagen  passat    3.6  2008    6    auto(s6)   f   17   26  p   

       class  
1    compact  
2    compact  
3    compact  
4    compact  
5    compact  
..       ...  
230  midsize  
231  midsize  
232  midsize  
233  midsize  
234  midsize  

[234 rows x 11 columns]

In [114]:
#look at info
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 234 entries, 1 to 234
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   manufacturer  234 non-null    object 
 1   model         234 non-null    object 
 2   displ         234 non-null    float64
 3   year          234 non-null    int64  
 4   cyl           234 non-null    int64  
 5   trans         234 non-null    object 
 6   drv           234 non-null    object 
 7   cty           234 non-null    int64  
 8   hwy           234 non-null    int64  
 9   fl            234 non-null    object 
 10  class         234 non-null    object 
dtypes: float64(1), int64(4), object(6)
memory usage: 21.9+ KB


In [115]:
#use .nunique to see which columns have categorical variables
df.nunique()

manufacturer    15
model           38
displ           35
year             2
cyl              4
trans           10
drv              3
cty             21
hwy             27
fl               5
class            7
dtype: int64

In [116]:
#look at year data
df.year.value_counts()

1999    117
2008    117
Name: year, dtype: int64

In [117]:
#look at cyl data
df.cyl.value_counts()

4    81
6    79
8    70
5     4
Name: cyl, dtype: int64

### Form hypothesis

$H_o$: there is no association between the car year and cylinder

$H_a$: there is a association between the car year and cylinder

### Make contigency table

In [118]:
observed = pd.crosstab(df.year, df.cyl)
observed

cyl    4  5   6   8
year               
1999  45  0  45  27
2008  36  4  34  43

### Calculate $chi^2$ and p-value

In [119]:
chi2, p, degf, expected = stats.chi2_contingency(observed)

In [120]:
#output values
print('Observed')
print(observed.values)
print('\nExpected')
print(expected.astype(int))
print('\n----')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed
[[45  0 45 27]
 [36  4 34 43]]

Expected
[[40  2 39 35]
 [40  2 39 35]]

----
chi^2 = 10.1888
p     = 0.0170


### Conclude

In [121]:
if p < alpha:
    print('We reject the null hypothesis')
else:
    print('We fail to reject the null hypothesis')

We reject the null hypothesis


## Use the data from the employees database to answer these questions:

In [122]:
from env import get_connection
from sqlalchemy import create_engine, text

In [123]:
def get_db_url(database):
    return get_connection(database)

In [124]:
#set sql query and read in data
url = get_db_url('employees')
query = text("select emp_no, gender, dept_name from employees join dept_emp using (emp_no) join departments using (dept_no) where to_date = '9999-01-01' and dept_name in ('Marketing','Sales')")
engine = create_engine(url)
df = pd.read_sql(query, engine.connect())
df

emp_no gender  dept_name
0       10017      F  Marketing
1       10058      M  Marketing
2       10140      F  Marketing
3       10228      F  Marketing
4       10239      F  Marketing
...       ...    ...        ...
52538  499966      F      Sales
52539  499976      M      Sales
52540  499980      M      Sales
52541  499986      F      Sales
52542  499987      F      Sales

[52543 rows x 3 columns]

In [125]:
#view gender data
df.gender.value_counts()

M    31680
F    20863
Name: gender, dtype: int64

In [126]:
#view dept_name data
df.dept_name.value_counts()

Sales        37701
Marketing    14842
Name: dept_name, dtype: int64

In [127]:
#create contigency table
observed = pd.crosstab(df.gender, df.dept_name)
observed

dept_name  Marketing  Sales
gender                     
F               5864  14999
M               8978  22702

In [128]:
#calculate chi2 and p-value
chi2, p, degf, expected = stats.chi2_contingency(observed)

In [129]:
#output values
print('Observed')
print(observed.values)
print('\nExpected')
print(expected.astype(int))
print('\n----')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed
[[ 5864 14999]
 [ 8978 22702]]

Expected
[[ 5893 14969]
 [ 8948 22731]]

----
chi^2 = 0.3240
p     = 0.5692


In [130]:
#conclude
if p < alpha:
    print('We reject the null hypothesis')
else:
    print('We fail to reject the null hypothesis')

We fail to reject the null hypothesis


## Is an employee's gender independent of whether or not they are or have been a manager?

$H_o$: there is no association between being a persons gender and being a manager

$H_a$: there is a association between being a persons gender and being a manager

In [131]:
#set sql query and read in data
url = get_db_url('employees')
query = text("SELECT emp_no, gender, dept_no FROM employees LEFT JOIN dept_manager USING (emp_no)")
engine = create_engine(url)
df = pd.read_sql(query, engine.connect())
df

emp_no gender dept_no
0        10001      M    None
1        10002      F    None
2        10003      M    None
3        10004      M    None
4        10005      M    None
...        ...    ...     ...
300019  499995      F    None
300020  499996      M    None
300021  499997      M    None
300022  499998      M    None
300023  499999      M    None

[300024 rows x 3 columns]

In [132]:
#look at data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300024 entries, 0 to 300023
Data columns (total 3 columns):
 #   Column   Non-Null Count   Dtype 
---  ------   --------------   ----- 
 0   emp_no   300024 non-null  int64 
 1   gender   300024 non-null  object
 2   dept_no  24 non-null      object
dtypes: int64(1), object(2)
memory usage: 6.9+ MB


In [133]:
#look at dept_no data
df.dept_no.value_counts(dropna=False)

None    300000
d004         4
d006         4
d009         4
d001         2
d002         2
d003         2
d005         2
d007         2
d008         2
Name: dept_no, dtype: int64

In [134]:
#fill in nulls
df.dept_no = df.dept_no.fillna('not manager')

In [135]:
df.dept_no.value_counts()

not manager    300000
d004                4
d006                4
d009                4
d001                2
d002                2
d003                2
d005                2
d007                2
d008                2
Name: dept_no, dtype: int64

In [136]:
#make new column using np.where
# np.where( condtion, this happens when true, this happens when false)
df.dept_no = np.where( df.dept_no != 'not manager', 'manager', 'not manager')

In [137]:
df.dept_no.value_counts()

not manager    300000
manager            24
Name: dept_no, dtype: int64

In [138]:
#create contigency table
observed = pd.crosstab(df.gender, df.dept_no)
observed

dept_no  manager  not manager
gender                       
F             13       120038
M             11       179962

In [139]:
#calculate chi2 and p-value
chi2, p, degf, expected = stats.chi2_contingency(observed)

In [140]:
#output values
print('Observed')
print(observed.values)
print('\nExpected')
print(expected.astype(int))
print('\n----')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed
[[    13 120038]
 [    11 179962]]

Expected
[[     9 120041]
 [    14 179958]]

----
chi^2 = 1.4567
p     = 0.2275


In [141]:
#conclude
if p < alpha:
    print('We reject the null hypothesis')
else:
    print("we fail to reject the null hypothesis")

we fail to reject the null hypothesis
